### PR TITLE
Removed gson and jsoup dependencies

### PR DESCRIPTION
**Pull request by andrewpros**
Beta request fix https://github.com/hummatli/MAHAndroidUpdater/pull/13#issuecomment-278879120

### CODE REVIEW

**Comment by hummatli** [comment]
Ok, @andrewpros . I will accept it. Thx.

**Comment by hummatli** [comment]
Hi, @andrewpros . There are was some bugs in code I reverted it and I thing there is not so many demand to clear gson and jsoup libraries from project. These third party libs easies our jobs.

Therefore I will not accpet next request based on this changes.

Regards, Sattar Hummatli

**Comment by andrewpros** [comment]
@hummatli It eases nothing, and is not needed for anything, i will not install 3rd party libs for such simple functionality, developers are this days so lazy, the simplest thing done by 3rd party lib, and they call themselves "developers".

If so, ok then, i'm done with supporting this project publicly, sorry, not the kind of project i want to be part of, i will make my private fork then with all improvements.

**Comment by hummatli** [comment]
@andrewpros . If its not helpful for you don't use it. There are people need it [jcenter statistics](https://bintray.com/hummatli/maven/mah-android-updater#statistics)

I have done this for my own use and then opened it for community. This all done by my effort. I have spend a lot off time on it learning and improving. But I can not spend all my time here.

It 's all with rule. Do what ever with your fork. 

And finally be part of what ever you want nobody asked you to join . Your needs brought you here.

**Comment by hummatli** [comment]
@andrewpros .And about your changes:

I thing there is not so many use full arguments to change working and tested (by me) project (with jsoup and gson) to a unstable new version (with raw methods). 
Your last changes was not life weight enough for project. 

You thing that I don't know What is JSONObject and HttpURLConnection. I couldn't use it?

Can you show me enough reason why I have to change these methods to a raw methods?

**Comment by andrewpros** [comment]
Devs are lazy this days, there is absolute no point in using  TWO LIBRARIES just for such simple things, this is insane, many project already using in their projects some libs and they are different than jsoup and gson, so why to bloat apps that want to use your project by another deps, no point at all.

**Pull request merged**
