### PR TITLE
Revert "Removed gson and jsoup dependencies"

### PR DESCRIPTION
**Pull request by hummatli**
Reverts hummatli/MAHAndroidUpdater#14

It gives NullPointer exceptions in some points. Needs to be tested.

### CODE REVIEW

**Comment by andrewpros** [comment]
@hummatli Why test if you will not accept it? SO what, your waiting someone to do your job and test, why didn't you test it, i had zero errors, what were the errors, where? Better close it, i'm done with such "collaboration"

**Comment by hummatli** [comment]
@andrewpros . I tested it and saw two bugs, But I have not time to spend all this one project. I have another jobs.

Every contributor has to test changes first. I am not a tester. I can help further.
I can spend a little more effort if it is very important feature which was your first contribution (This is not)

**There were two NullPointerExceptions in the code. You can check it.**
1) If programInfo  is null. (This happens when there is problem with service and program info will be null. ) [Look at here](https://github.com/hummatli/MAHAndroidUpdater/pull/15/files#diff-79a48f3d74ed297f77574659d5ef2915L46)
2) If json string is null.  (This will happen in first time, if there is not internet connection and cache ) [Look at here](https://github.com/hummatli/MAHAndroidUpdater/pull/15/files#diff-79a48f3d74ed297f77574659d5ef2915L69)
3) I didn't investigate further.

**Comment by andrewpros** [comment]
@hummatli Ok, but i'm not alpha and omega, mistakes happen.

But you explicitly said 

> Therefore I will not accpet next request based on this changes.

So whats the point now? If you have no time and wont even accept it, in this situation i have no guarantee other changes would be accepted either.

And if you have no time and wont even accept anything new, then what, is this project dead, looks like it.

It is easy to modify, simple, that is why i choose it, minimum code, bu tit lacks features for more advanced fine tuning and bloats the project, so i need changes.

**Comment by hummatli** [comment]
@andrewpros , Project is not dead. 

Your previous request was awesome. Therefore I accepted it and spend time on testing it.

I know bugs everywhere. Even in large projects like Picasso, Glide and so on. has a lot of bugs. I don't blame you 👍.  

I respect your effort and labor. But sorry I thing last request does not worth to spend time on it (My thoughts). Yes it seems like we try to change small portion of code, But these parts are core processes of the project. 

You know, this is Android. There happens bugs in some devices you don't even imagine how this is possible.  If I accept this changes I have to test all over from start.

There is not such rule that every request has to be merged to the main project. I have contributed to other projects but not all off them accepted. If you thing this functionality is so important you can do it on your own fork.

So sorry . Let's end this discussion. 

I see you are very talented guy 👍  , If you have another good awesome idea we can discuss it with you. I have another projects too. If you are interested we can work on them too. They need additional features. But I have not time to do them right now alone.

Best regards , Sattar Hummatli.

**Comment by andrewpros** [comment]
@hummatli Yeah better bloat the whole project with libs cuz you can't do simple things with android api only. That awesome. Another lazy dev.

**Pull request merged**
