### PR TITLE
Added update info resolver option

### PR DESCRIPTION
**Pull request by andrewpros**
PR for discussion https://github.com/hummatli/MAHAndroidUpdater/issues/10

@hummatli

### CODE REVIEW

**Comment by hummatli** [comment]
Awesome, @andrewpros 

You have done great job.

Give me time to analyze. I will merge it soon.

**Comment by andrewpros** [comment]
@hummatli Thx, no need to hurry.

**Comment by hummatli** [comment]
Hi , @andrewpros. You have done great job.

* I have merged your changes to master.
* Released new version (v1.1.5)
* Added some information to Readme [about you])(https://github.com/hummatli/MAHAndroidUpdater#contributors)  and [about info resolver](https://github.com/hummatli/MAHAndroidUpdater#service-structure). Modify them if you want.



- This is  [my face account](https://www.facebook.com/hummatli).Request me I want to be friend with you. :)
- Don't forget to star project in Github 👍 

And will share this reales i Facebook want to mention you in the post.

Regards. Sattar Hummatli.

**Comment by andrewpros** [comment]
@hummatli "Well that escalated quickly"

Nice! Quick release, now i will use it from gradle.

Maybe i will propose some other changes, we don't really need jsoup, gson, it would be nice to have also some "LATER" button options, like configurable update dialog reappearance time, not every time app launches.

**Comment by hummatli** [comment]
@andrewpros , 

ok, great idea.
 
You have not face account?

**Comment by hummatli** [comment]
Hi, @andrewpros .

* Want you add your app to the [applications-using-mahandroidupdater list](https://github.com/hummatli/MAHAndroidUpdater#applications-using-mahandroidupdater) .? I would be very good for your app and for this project
* I don't know why but your name does not listed in [contributors list](https://github.com/hummatli/MAHAndroidUpdater/graphs/contributors). It has to be added automatically after merging your pull request. Do you know something about this?

**Comment by andrewpros** [comment]
@hummatli No, my app is private so i can't.

And i didn't done this for fame, so i don't need to be in contributors.

**Comment by hummatli** [comment]
Ok. @andrewpros.

This is great!
Thanks!

**Pull request merged**
