### PR TITLE
fr translate

### PR DESCRIPTION
**Pull request by Zeldarck**
Do without context, may be some typo

### CODE REVIEW

**Comment by hummatli** [comment]
Hi, @Zeldarck . I appreciate your efforts. But translation are more wordy and if we consider some sentence are int dialog titles and in buttons titles they will look very unconvenient.  I would very happy if you can translate with context and will accept it as translation 👍  :)

**Comment by Zeldarck** [comment]
OK, I will try :)
Wich one are too longer? Open New and Uninstall old? I will try to find a better mean to say that two

**Comment by Zeldarck** [comment]
I don't find in app exemple where are use Open New and Uninstall Old, if the precision of "new" and "old" are not necessary, It will reduce the size of the text to "Ouvrir" and "Désinstaller".
If in the dialog box it's say we speak of versions and not necessary to say it again in buttons we can put "Ouvrir la nouvelle" and "Désinstaller l'ancienne"

For the other text, I don't see liek that wich one need to be reduce :)

**Comment by hummatli** [comment]
Ok. Fine. 👍  I will list the items need to be shorten ASAP :)

**Comment by hummatli** [comment]
I think rest are normal. 

But set followings and send pull request

This versions are convenient , there is no need for "version" word it can be eliminated 
* Update Information - Informations de mise à jour
* Open new version - Ouvrir la nouvelle 
* Open old -  Désinstaller l'ancienne

**Comment by Zeldarck** [comment]
It's ok like that?

**Comment by hummatli** [comment]
Yeah, all is cool 👍 . I am accepting it and if you want add your name to the contributors list in Readme.MD 

And further, it would be awesome if you could add the French lang option in Sample app too 🥇 

Regards, Sattar Hummatli

**Comment by Zeldarck** [comment]
No problem,where is the lang file of the sample? 
I found only that : 
AndroidAppUpdater/sample-app/src/main/res/values/string.xml

**Comment by hummatli** [comment]
It is four places:
* [SampleActivityKotlin.kt - 1]( https://github.com/hummatli/AndroidAppUpdater/blob/master/sample-app/src/main/java/com/mobapphome/mahandroidupdater/sample/SampleActivityKotlin.kt#L68)
* [SampleActivityKotlin.kt - 2]( https://github.com/hummatli/AndroidAppUpdater/blob/master/sample-app/src/main/java/com/mobapphome/mahandroidupdater/sample/SampleActivityKotlin.kt#L98)
* [SampleActivityJava.java - 1]( https://github.com/hummatli/AndroidAppUpdater/blob/master/sample-app/src/main/java/com/mobapphome/mahandroidupdater/sample/SampleActivityJava.java#L66)
* [SampleActivityJava.java - 2]( https://github.com/hummatli/AndroidAppUpdater/blob/master/sample-app/src/main/java/com/mobapphome/mahandroidupdater/sample/SampleActivityJava.java#L88)

Contributors list
* [contributors](https://github.com/hummatli/AndroidAppUpdater#contributors)

Applications list using this. Add your app here if you use it
* [Applications Using](https://github.com/hummatli/AndroidAppUpdater#applications-using-mahandroidupdater)

**Comment by Zeldarck** [comment]
I did pull reaquest there is 2 more place with a list of langage if files linked,I added french too :)

no need of contributor and I didn't use it, I searched for a Unity project in IoS and Android, I think I will use a file on a server to check version of the store.

**Comment by hummatli** [comment]
Oooo, Thanks friend, you are awesome 👍 . Yes I have forgotten about two items :)

I will add your name to contributors if you let.  it's for favour to project.

You mean you liked backend and you wanna use it in your Unity project backend ?! Do I understand right?  

If so, you can generate client part as an open source project in github and use it in your application and we can contribute it together. Yes I don't now Unity much more , but I am planing to learn it. 

I have done this project in this way and this projects will be different clients of the same project and will work with the same backend. 

And it will be use full for all (us, to you project as well 🥇)

**Comment by Zeldarck** [comment]
Yeah you can add me, no problem :)

I am not sure to well understand. I have an Unity game, and I would like when we open the game a popup said to the player if a more recent version exist on Apple Store on IoS/Google Play on android, and eventually allow him to download the new version. The game is local so he can play without do the update.
When I searched for that purpose I found that git. But when I have tell the differents solution to my direction, they prefere keep simple and just put a file with the version on our server and read it at the launch of the application.

I am a trainee and I developped my skill, I am newbie in Unity too, maybe when I will got a little more experience I will back to do this, but now I have a lot to learn on Unity before I think :)

**Comment by hummatli** [comment]
Yes you are right. This library is for the same purposes but for native Android applications. 

But I don't think it's suitable for Unity games, cause native Android apps has different framework.

You can after developing your games extract that part and create additional library for this purposes.   👍 

Good luck in your learning process. I am planning to learn Unity too.

This my [face account ](https://www.facebook.com/hummatli)   Send request if you wanna contact with me there. 

And don't forget to start this project if you really liked it . 

Thanks! :)

**Comment by Zeldarck** [comment]
I really don't know, I never devellop in native Android ^^"

Thank you :)

I added you

**Pull request merged**
